version: '3.8'

services:
  openvpn:
    container_name: openvpn-server
    build:
      context: .
      dockerfile: Dockerfile
    image: openvpn-server:latest
    restart: unless-stopped

    # Сетевые настройки
    ports:
      - "1194:1194/udp"

    # Привилегии для работы с сетью
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    # Устройства
    devices:
      - /dev/net/tun:/dev/net/tun

    # Volumes для постоянного хранения данных
    volumes:
      - openvpn_data:/etc/openvpn
      - openvpn_logs:/var/log/openvpn
      - ./client-configs:/client-configs
      - /lib/modules:/lib/modules:ro

    # Переменные окружения
    environment:
      - OPENVPN_SERVER_IP=${OPENVPN_SERVER_IP:-localhost}
      - OPENVPN_PORT=1194
      - OPENVPN_PROTOCOL=udp
      - OPENVPN_NETWORK=10.8.0.0
      - OPENVPN_NETMASK=255.255.255.0
      - OPENVPN_DNS1=1.1.1.1
      - OPENVPN_DNS2=1.0.0.1

    # Сетевые настройки
    networks:
      - openvpn_network

    # Системные настройки
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1

    # Настройки безопасности
    security_opt:
      - no-new-privileges:true

    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "openvpn"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Volumes
volumes:
  openvpn_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/openvpn-docker/data

  openvpn_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/openvpn-docker/logs

# Networks
networks:
  openvpn_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.bridge.name: openvpn0
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: 1500